version: '3.7'
services:
  pict:
    image: mitxela/pict
    ports:
      - 80:80

    # Disable SSL for local usage
    environment:
      PICT_NO_SSL: yes_please_no_ssl_thanks

    # Mount local source directory into image, to be able to work on it live.
    volumes:
     - type: bind
       source: ../src
       target: /app
