version: '3.7'
services:
  pict:
    image: mitxela/pict
    ports:
      - 80:80

    environment:
      # Disable SSL for local usage
      PICT_NO_SSL: yes_please_no_ssl_thanks
      JS_POLL_TIME: 1000

    # Mount local source directory into image, to be able to work on it live.
    volumes:
     - type: bind
       source: ../src
       target: /opt/app
