version: '3.7'
services:
  pict:
    image: mitxela/pict
    ports:
      - 80:80

    # Mount local source directory into image, to be able to work on it live.
    volumes:
     - type: bind
       source: ../src
       target: /opt/app
