version: '3.7'
services:
  pict:
    image: mitxela/pict
    ports:
      - 80:80
    environment:
      #CREATE_MYSQL_USER: 'true'
      MYSQL_USER_NAME: pict
      MYSQL_USER_DB: pict
      MYSQL_USER_PASS: pict
    volumes:
     - type: bind
       source: ./src
       target: /app
