#!/bin/sh

exec 2>&1

[ -d /opt/data ] || (
	>&2 echo installing mysql data directory...
	mkdir -p /opt/data_create
	mysql_install_db --user=mysql --datadir=/opt/data_create --auth-root-authentication-method=normal
	mv /opt/data_create /opt/data
)

mkdir -p /opt/app/img
chown nobody /opt/app/img

while : ; do
	>&2 echo waiting for mysql to come up...
	(echo 'select '\'mysql is up\' situation';' | mysql -u root) && break
	sleep 1
done

>&2 echo trying to create database...
echo 'create database pict;' | mysql -u root

>&2 echo trying to populate schema...
(mysql -u root pict < /opt/pict.sql) && break

>&2 echo SCHEMA is GOOD
