#!/bin/sh

[ -d /opt/data ] || (
	>&2 echo installing mysql data directory...
	mkdir -p /opt/data_create
	mysql_install_db --user=mysql --datadir=/opt/data_create --auth-root-authentication-method=normal
	mv /opt/data_create /opt/data
)

mkdir -p /opt/app/img
chown nobody /opt/app/img

while ! (echo 'create database pict;' | mysql -u root); do
	sleep 1
	>&2 echo trying to create database
done
while ! (mysql -u root pict < /opt/pict.sql); do
	sleep 1
	>&2 echo trying to populate schema
done

>&2 echo SCHEMA is GOOD
